### ISSUE TITLE
On iOS 16 the video controls are not shown

### ISSUE THREAD

**Issue by Auto72** [pro777s/Xam.Forms.VideoPlayer#13]
On iOS 16 the video controls are not shown.
Is there a way to show them?
I found a post about it here:
https://learn.microsoft.com/en-us/answers/questions/1051168/xamarin-forms-ios-16-avplayer-not-showing-video-co

Can this been fixed?
Thanks.

**Comment by jamesdlow** [comment]
Having this issue too!
