### ISSUE TITLE
AreTransportControlsEnabled  **System.NullReferenceException:** 'Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by gsemenov** [pro777s/Xam.Forms.VideoPlayer#4]
my goal was to hide control panel.
when I set AreTransportControlsEnabled = false I got **System.NullReferenceException:** 'Object reference not set to an instance of an object.

**Comment by pro777s** [comment]
@gsemenov, thanks for the error info. Fixed in version 1.0.6.
